### ISSUE TITLE
Works at Hogeschool Gent, Ghent, Belgium

### ISSUE THREAD

**Issue by VictorVanWeyenberg** [oleks/eduroam-wpa_supplicant#27]
Just made it work at Hogeschool Gent.

The staff didn't know about this method so I'll make sure they get a reference to this repo.

Thanks a lot!

**Comment by oleks** [comment]
Did you try [The eduroam Configuration Assistant Tool (CAT)](https://cat.eduroam.org/)?

**Comment by VictorVanWeyenberg** [comment]
Haha, that would've been handy!
No, I used your the wpa_supplicant method as described in your README.md.

**Comment by VictorVanWeyenberg** [comment]
Shortly after I managed to get the eduroam connection it suddenly stopped working.
I now tried CAT. I don't get connection and it keeps asking for my password. It doesn't say I entered wrong credentials, I only get the "Authentication required" screen.

I use Linux Mint 18.3.

**Comment by oleks** [comment]
Are you using the ["Quick and dirty start-up" method](https://github.com/oleks/eduroam-wpa_supplicant#quick-and-dirty-start-up) to spin up `wpa_supplicant`? Because then you can omit the `-B` option and get more detailed information.

You can get even more detailed (debug) information, by passing in the `-d` or `-dd` option. Also, to get `wpa_supplicant` to write to a file instead of stdout, use the `-f` option. For more, see [`man 8 wpa_supplicant`](https://linux.die.net/man/8/wpa_supplicant).

**Comment by oleks** [comment]
If you are relying on your Linux Mint installation to start up `wpa_supplicant`, I think you should be looking for log messages from `wpa_supplicant` in your syslog (i.e., `/var/log/syslog`). In either case, we need some more information than "suddenly stopped working" ;-)

By the way, it might have "stopped working" precisely because your system is starting one instance of `wpa_supplicant`, and then you manually start another using the [`"Quick and dirty start-up" method](https://github.com/oleks/eduroam-wpa_supplicant#quick-and-dirty-start-up). These two instances then compete for your network card, resulting in things that "suddenly" stop working.

**Comment by VictorVanWeyenberg** [comment]
Thanks but nevermind.
I noticed I wasn't even able to connect to my home network. (It's quite an old machine.) Restarting the system solved the problem and I haven't had any problems with my connection to either my home network or eduroam.
Sorry for the hassle. Everything is working fine.
